#!/usr/bin/env python3
import sys
import base64

def main():
    if not sys.stdin.isatty():
        input_bytes = sys.stdin.buffer.read()
    elif len(sys.argv) > 1:
        input_bytes = ' '.join(sys.argv[1:]).encode()
    else:
        input_bytes = b''

    if input_bytes:
        encoded = base64.b64encode(input_bytes)
        print(encoded.decode(), end='')

if __name__ == "__main__":
    main()
